/* Auto-generated by genmsg_cpp for file /home/vsunder/ButlerBot/rosbuild_ws/src/controller_manager/msg/ReleaseController.msg */
#ifndef CONTROLLER_MANAGER_MESSAGE_RELEASECONTROLLER_H
#define CONTROLLER_MANAGER_MESSAGE_RELEASECONTROLLER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace controller_manager
{
template <class ContainerAllocator>
struct ReleaseController_ {
  typedef ReleaseController_<ContainerAllocator> Type;

  ReleaseController_()
  : controller()
  {
  }

  ReleaseController_(const ContainerAllocator& _alloc)
  : controller(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _controller_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  controller;


  typedef boost::shared_ptr< ::controller_manager::ReleaseController_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller_manager::ReleaseController_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ReleaseController
typedef  ::controller_manager::ReleaseController_<std::allocator<void> > ReleaseController;

typedef boost::shared_ptr< ::controller_manager::ReleaseController> ReleaseControllerPtr;
typedef boost::shared_ptr< ::controller_manager::ReleaseController const> ReleaseControllerConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::controller_manager::ReleaseController_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::controller_manager::ReleaseController_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace controller_manager

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controller_manager::ReleaseController_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controller_manager::ReleaseController_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controller_manager::ReleaseController_<ContainerAllocator> > {
  static const char* value() 
  {
    return "36383e0f0fa46585abbab8aedd87321a";
  }

  static const char* value(const  ::controller_manager::ReleaseController_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x36383e0f0fa46585ULL;
  static const uint64_t static_value2 = 0xabbab8aedd87321aULL;
};

template<class ContainerAllocator>
struct DataType< ::controller_manager::ReleaseController_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controller_manager/ReleaseController";
  }

  static const char* value(const  ::controller_manager::ReleaseController_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controller_manager::ReleaseController_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string controller\n\
\n\
";
  }

  static const char* value(const  ::controller_manager::ReleaseController_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controller_manager::ReleaseController_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.controller);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ReleaseController_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller_manager::ReleaseController_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::controller_manager::ReleaseController_<ContainerAllocator> & v) 
  {
    s << indent << "controller: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.controller);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MANAGER_MESSAGE_RELEASECONTROLLER_H

