/* Auto-generated by genmsg_cpp for file /home/vsunder/ButlerBot/rosbuild_ws/src/behaviors/msg/Activate.msg */
#ifndef BEHAVIORS_MESSAGE_ACTIVATE_H
#define BEHAVIORS_MESSAGE_ACTIVATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace behaviors
{
template <class ContainerAllocator>
struct Activate_ {
  typedef Activate_<ContainerAllocator> Type;

  Activate_()
  : behavior()
  , params()
  {
  }

  Activate_(const ContainerAllocator& _alloc)
  : behavior(_alloc)
  , params(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _behavior_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  behavior;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _params_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  params;


  typedef boost::shared_ptr< ::behaviors::Activate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviors::Activate_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Activate
typedef  ::behaviors::Activate_<std::allocator<void> > Activate;

typedef boost::shared_ptr< ::behaviors::Activate> ActivatePtr;
typedef boost::shared_ptr< ::behaviors::Activate const> ActivateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::behaviors::Activate_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::behaviors::Activate_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace behaviors

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::behaviors::Activate_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::behaviors::Activate_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::behaviors::Activate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "21aa9db2d3610b5442ceef9214241d8b";
  }

  static const char* value(const  ::behaviors::Activate_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x21aa9db2d3610b54ULL;
  static const uint64_t static_value2 = 0x42ceef9214241d8bULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviors::Activate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "behaviors/Activate";
  }

  static const char* value(const  ::behaviors::Activate_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::behaviors::Activate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string behavior\n\
string params\n\
\n\
";
  }

  static const char* value(const  ::behaviors::Activate_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::behaviors::Activate_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.behavior);
    stream.next(m.params);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Activate_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviors::Activate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::behaviors::Activate_<ContainerAllocator> & v) 
  {
    s << indent << "behavior: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.behavior);
    s << indent << "params: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.params);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BEHAVIORS_MESSAGE_ACTIVATE_H

