/* Auto-generated by genmsg_cpp for file /home/vsunder/ButlerBot/rosbuild_ws/src/behaviors/msg/Completed.msg */
#ifndef BEHAVIORS_MESSAGE_COMPLETED_H
#define BEHAVIORS_MESSAGE_COMPLETED_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace behaviors
{
template <class ContainerAllocator>
struct Completed_ {
  typedef Completed_<ContainerAllocator> Type;

  Completed_()
  : behavior()
  , error(0)
  {
  }

  Completed_(const ContainerAllocator& _alloc)
  : behavior(_alloc)
  , error(0)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _behavior_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  behavior;

  typedef int8_t _error_type;
  int8_t error;


  typedef boost::shared_ptr< ::behaviors::Completed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviors::Completed_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Completed
typedef  ::behaviors::Completed_<std::allocator<void> > Completed;

typedef boost::shared_ptr< ::behaviors::Completed> CompletedPtr;
typedef boost::shared_ptr< ::behaviors::Completed const> CompletedConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::behaviors::Completed_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::behaviors::Completed_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace behaviors

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::behaviors::Completed_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::behaviors::Completed_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::behaviors::Completed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5360d8dc63ebb508e9d3b0ff75130e31";
  }

  static const char* value(const  ::behaviors::Completed_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5360d8dc63ebb508ULL;
  static const uint64_t static_value2 = 0xe9d3b0ff75130e31ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviors::Completed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "behaviors/Completed";
  }

  static const char* value(const  ::behaviors::Completed_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::behaviors::Completed_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string behavior\n\
int8 error\n\
\n\
";
  }

  static const char* value(const  ::behaviors::Completed_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::behaviors::Completed_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.behavior);
    stream.next(m.error);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Completed_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviors::Completed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::behaviors::Completed_<ContainerAllocator> & v) 
  {
    s << indent << "behavior: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.behavior);
    s << indent << "error: ";
    Printer<int8_t>::stream(s, indent + "  ", v.error);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BEHAVIORS_MESSAGE_COMPLETED_H

