/* Auto-generated by genmsg_cpp for file /home/vsunder/ButlerBot/rosbuild_ws/src/behaviors/msg/Recs.msg */
#ifndef BEHAVIORS_MESSAGE_RECS_H
#define BEHAVIORS_MESSAGE_RECS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace behaviors
{
template <class ContainerAllocator>
struct Recs_ {
  typedef Recs_<ContainerAllocator> Type;

  Recs_()
  : behavior()
  , rec()
  {
  }

  Recs_(const ContainerAllocator& _alloc)
  : behavior(_alloc)
  , rec(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _behavior_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  behavior;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _rec_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  rec;


  typedef boost::shared_ptr< ::behaviors::Recs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviors::Recs_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Recs
typedef  ::behaviors::Recs_<std::allocator<void> > Recs;

typedef boost::shared_ptr< ::behaviors::Recs> RecsPtr;
typedef boost::shared_ptr< ::behaviors::Recs const> RecsConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::behaviors::Recs_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::behaviors::Recs_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace behaviors

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::behaviors::Recs_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::behaviors::Recs_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::behaviors::Recs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "397fd470c422f6c937d75f1c3e825400";
  }

  static const char* value(const  ::behaviors::Recs_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x397fd470c422f6c9ULL;
  static const uint64_t static_value2 = 0x37d75f1c3e825400ULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviors::Recs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "behaviors/Recs";
  }

  static const char* value(const  ::behaviors::Recs_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::behaviors::Recs_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string behavior\n\
string rec\n\
\n\
";
  }

  static const char* value(const  ::behaviors::Recs_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::behaviors::Recs_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.behavior);
    stream.next(m.rec);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Recs_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviors::Recs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::behaviors::Recs_<ContainerAllocator> & v) 
  {
    s << indent << "behavior: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.behavior);
    s << indent << "rec: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.rec);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BEHAVIORS_MESSAGE_RECS_H

