/* Auto-generated by genmsg_cpp for file /home/vsunder/ButlerBot/rosbuild_ws/src/behaviors/msg/Startup.msg */
#ifndef BEHAVIORS_MESSAGE_STARTUP_H
#define BEHAVIORS_MESSAGE_STARTUP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace behaviors
{
template <class ContainerAllocator>
struct Startup_ {
  typedef Startup_<ContainerAllocator> Type;

  Startup_()
  : behavior()
  {
  }

  Startup_(const ContainerAllocator& _alloc)
  : behavior(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _behavior_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  behavior;


  typedef boost::shared_ptr< ::behaviors::Startup_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behaviors::Startup_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Startup
typedef  ::behaviors::Startup_<std::allocator<void> > Startup;

typedef boost::shared_ptr< ::behaviors::Startup> StartupPtr;
typedef boost::shared_ptr< ::behaviors::Startup const> StartupConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::behaviors::Startup_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::behaviors::Startup_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace behaviors

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::behaviors::Startup_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::behaviors::Startup_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::behaviors::Startup_<ContainerAllocator> > {
  static const char* value() 
  {
    return "03729983c4b9be7a4f2b56846a7ccbdc";
  }

  static const char* value(const  ::behaviors::Startup_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x03729983c4b9be7aULL;
  static const uint64_t static_value2 = 0x4f2b56846a7ccbdcULL;
};

template<class ContainerAllocator>
struct DataType< ::behaviors::Startup_<ContainerAllocator> > {
  static const char* value() 
  {
    return "behaviors/Startup";
  }

  static const char* value(const  ::behaviors::Startup_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::behaviors::Startup_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string behavior\n\
\n\
";
  }

  static const char* value(const  ::behaviors::Startup_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::behaviors::Startup_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.behavior);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Startup_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behaviors::Startup_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::behaviors::Startup_<ContainerAllocator> & v) 
  {
    s << indent << "behavior: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.behavior);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BEHAVIORS_MESSAGE_STARTUP_H

