/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/vsunder/ButlerBot/catkin_ws/src/Behaviors/msg/Recs.msg
 *
 */


#ifndef BEHAVIORS_MESSAGE_RECS_H
#define BEHAVIORS_MESSAGE_RECS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Behaviors
{
template <class ContainerAllocator>
struct Recs_
{
  typedef Recs_<ContainerAllocator> Type;

  Recs_()
    : behavior()
    , priority(0)
    , recommendation()  {
    }
  Recs_(const ContainerAllocator& _alloc)
    : behavior(_alloc)
    , priority(0)
    , recommendation(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _behavior_type;
  _behavior_type behavior;

   typedef uint8_t _priority_type;
  _priority_type priority;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _recommendation_type;
  _recommendation_type recommendation;




  typedef boost::shared_ptr< ::Behaviors::Recs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Behaviors::Recs_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Recs_

typedef ::Behaviors::Recs_<std::allocator<void> > Recs;

typedef boost::shared_ptr< ::Behaviors::Recs > RecsPtr;
typedef boost::shared_ptr< ::Behaviors::Recs const> RecsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Behaviors::Recs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Behaviors::Recs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Behaviors

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'Behaviors': ['/home/vsunder/ButlerBot/catkin_ws/src/Behaviors/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Behaviors::Recs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Behaviors::Recs_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Behaviors::Recs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Behaviors::Recs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Behaviors::Recs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Behaviors::Recs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Behaviors::Recs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7876aadc4b52c34c6c94300ba5258e3b";
  }

  static const char* value(const ::Behaviors::Recs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7876aadc4b52c34cULL;
  static const uint64_t static_value2 = 0x6c94300ba5258e3bULL;
};

template<class ContainerAllocator>
struct DataType< ::Behaviors::Recs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Behaviors/Recs";
  }

  static const char* value(const ::Behaviors::Recs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Behaviors::Recs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string behavior\n\
uint8 priority\n\
string recommendation\n\
\n\
";
  }

  static const char* value(const ::Behaviors::Recs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Behaviors::Recs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.behavior);
      stream.next(m.priority);
      stream.next(m.recommendation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Recs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Behaviors::Recs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Behaviors::Recs_<ContainerAllocator>& v)
  {
    s << indent << "behavior: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.behavior);
    s << indent << "priority: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.priority);
    s << indent << "recommendation: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.recommendation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIORS_MESSAGE_RECS_H
