/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/vsunder/ButlerBot/catkin_ws/src/Intelligence/srv/EnableComs.srv
 *
 */


#ifndef INTELLIGENCE_MESSAGE_ENABLECOMS_H
#define INTELLIGENCE_MESSAGE_ENABLECOMS_H

#include <ros/service_traits.h>


#include <Intelligence/EnableComsRequest.h>
#include <Intelligence/EnableComsResponse.h>


namespace Intelligence
{

struct EnableComs
{

typedef EnableComsRequest Request;
typedef EnableComsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableComs
} // namespace Intelligence


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Intelligence::EnableComs > {
  static const char* value()
  {
    return "0376114d6a21b0b97ee0d71bfca6c78e";
  }

  static const char* value(const ::Intelligence::EnableComs&) { return value(); }
};

template<>
struct DataType< ::Intelligence::EnableComs > {
  static const char* value()
  {
    return "Intelligence/EnableComs";
  }

  static const char* value(const ::Intelligence::EnableComs&) { return value(); }
};


// service_traits::MD5Sum< ::Intelligence::EnableComsRequest> should match 
// service_traits::MD5Sum< ::Intelligence::EnableComs > 
template<>
struct MD5Sum< ::Intelligence::EnableComsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Intelligence::EnableComs >::value();
  }
  static const char* value(const ::Intelligence::EnableComsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Intelligence::EnableComsRequest> should match 
// service_traits::DataType< ::Intelligence::EnableComs > 
template<>
struct DataType< ::Intelligence::EnableComsRequest>
{
  static const char* value()
  {
    return DataType< ::Intelligence::EnableComs >::value();
  }
  static const char* value(const ::Intelligence::EnableComsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Intelligence::EnableComsResponse> should match 
// service_traits::MD5Sum< ::Intelligence::EnableComs > 
template<>
struct MD5Sum< ::Intelligence::EnableComsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Intelligence::EnableComs >::value();
  }
  static const char* value(const ::Intelligence::EnableComsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Intelligence::EnableComsResponse> should match 
// service_traits::DataType< ::Intelligence::EnableComs > 
template<>
struct DataType< ::Intelligence::EnableComsResponse>
{
  static const char* value()
  {
    return DataType< ::Intelligence::EnableComs >::value();
  }
  static const char* value(const ::Intelligence::EnableComsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTELLIGENCE_MESSAGE_ENABLECOMS_H
