/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/vsunder/ButlerBot/catkin_ws/src/Intelligence/srv/EnableComs.srv
 *
 */


#ifndef INTELLIGENCE_MESSAGE_ENABLECOMSREQUEST_H
#define INTELLIGENCE_MESSAGE_ENABLECOMSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Intelligence
{
template <class ContainerAllocator>
struct EnableComsRequest_
{
  typedef EnableComsRequest_<ContainerAllocator> Type;

  EnableComsRequest_()
    : enable_comlink(0)  {
    }
  EnableComsRequest_(const ContainerAllocator& _alloc)
    : enable_comlink(0)  {
    }



   typedef int8_t _enable_comlink_type;
  _enable_comlink_type enable_comlink;




  typedef boost::shared_ptr< ::Intelligence::EnableComsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Intelligence::EnableComsRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct EnableComsRequest_

typedef ::Intelligence::EnableComsRequest_<std::allocator<void> > EnableComsRequest;

typedef boost::shared_ptr< ::Intelligence::EnableComsRequest > EnableComsRequestPtr;
typedef boost::shared_ptr< ::Intelligence::EnableComsRequest const> EnableComsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Intelligence::EnableComsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Intelligence::EnableComsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Intelligence

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'Intelligence': ['/home/vsunder/ButlerBot/catkin_ws/src/Intelligence/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Intelligence::EnableComsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Intelligence::EnableComsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Intelligence::EnableComsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ecaa5859e6975165e93229ea44f7df70";
  }

  static const char* value(const ::Intelligence::EnableComsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xecaa5859e6975165ULL;
  static const uint64_t static_value2 = 0xe93229ea44f7df70ULL;
};

template<class ContainerAllocator>
struct DataType< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Intelligence/EnableComsRequest";
  }

  static const char* value(const ::Intelligence::EnableComsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 enable_comlink\n\
\n\
";
  }

  static const char* value(const ::Intelligence::EnableComsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable_comlink);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct EnableComsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Intelligence::EnableComsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Intelligence::EnableComsRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable_comlink: ";
    Printer<int8_t>::stream(s, indent + "  ", v.enable_comlink);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTELLIGENCE_MESSAGE_ENABLECOMSREQUEST_H
