/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/vsunder/ButlerBot/catkin_ws/src/BehaviorManager/srv/Startup.srv
 *
 */


#ifndef BEHAVIORMANAGER_MESSAGE_STARTUP_H
#define BEHAVIORMANAGER_MESSAGE_STARTUP_H

#include <ros/service_traits.h>


#include <BehaviorManager/StartupRequest.h>
#include <BehaviorManager/StartupResponse.h>


namespace BehaviorManager
{

struct Startup
{

typedef StartupRequest Request;
typedef StartupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Startup
} // namespace BehaviorManager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::BehaviorManager::Startup > {
  static const char* value()
  {
    return "bccc1c679fdd2d4249448e7f5e07e9e5";
  }

  static const char* value(const ::BehaviorManager::Startup&) { return value(); }
};

template<>
struct DataType< ::BehaviorManager::Startup > {
  static const char* value()
  {
    return "BehaviorManager/Startup";
  }

  static const char* value(const ::BehaviorManager::Startup&) { return value(); }
};


// service_traits::MD5Sum< ::BehaviorManager::StartupRequest> should match 
// service_traits::MD5Sum< ::BehaviorManager::Startup > 
template<>
struct MD5Sum< ::BehaviorManager::StartupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::BehaviorManager::Startup >::value();
  }
  static const char* value(const ::BehaviorManager::StartupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::BehaviorManager::StartupRequest> should match 
// service_traits::DataType< ::BehaviorManager::Startup > 
template<>
struct DataType< ::BehaviorManager::StartupRequest>
{
  static const char* value()
  {
    return DataType< ::BehaviorManager::Startup >::value();
  }
  static const char* value(const ::BehaviorManager::StartupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::BehaviorManager::StartupResponse> should match 
// service_traits::MD5Sum< ::BehaviorManager::Startup > 
template<>
struct MD5Sum< ::BehaviorManager::StartupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::BehaviorManager::Startup >::value();
  }
  static const char* value(const ::BehaviorManager::StartupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::BehaviorManager::StartupResponse> should match 
// service_traits::DataType< ::BehaviorManager::Startup > 
template<>
struct DataType< ::BehaviorManager::StartupResponse>
{
  static const char* value()
  {
    return DataType< ::BehaviorManager::Startup >::value();
  }
  static const char* value(const ::BehaviorManager::StartupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEHAVIORMANAGER_MESSAGE_STARTUP_H
