/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/vsunder/ButlerBot/catkin_ws/src/Behaviors/srv/ReserveBehavior.srv
 *
 */


#ifndef BEHAVIORS_MESSAGE_RESERVEBEHAVIOR_H
#define BEHAVIORS_MESSAGE_RESERVEBEHAVIOR_H

#include <ros/service_traits.h>


#include <Behaviors/ReserveBehaviorRequest.h>
#include <Behaviors/ReserveBehaviorResponse.h>


namespace Behaviors
{

struct ReserveBehavior
{

typedef ReserveBehaviorRequest Request;
typedef ReserveBehaviorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReserveBehavior
} // namespace Behaviors


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Behaviors::ReserveBehavior > {
  static const char* value()
  {
    return "36f8688ba68695f41095576c054c8604";
  }

  static const char* value(const ::Behaviors::ReserveBehavior&) { return value(); }
};

template<>
struct DataType< ::Behaviors::ReserveBehavior > {
  static const char* value()
  {
    return "Behaviors/ReserveBehavior";
  }

  static const char* value(const ::Behaviors::ReserveBehavior&) { return value(); }
};


// service_traits::MD5Sum< ::Behaviors::ReserveBehaviorRequest> should match 
// service_traits::MD5Sum< ::Behaviors::ReserveBehavior > 
template<>
struct MD5Sum< ::Behaviors::ReserveBehaviorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Behaviors::ReserveBehavior >::value();
  }
  static const char* value(const ::Behaviors::ReserveBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Behaviors::ReserveBehaviorRequest> should match 
// service_traits::DataType< ::Behaviors::ReserveBehavior > 
template<>
struct DataType< ::Behaviors::ReserveBehaviorRequest>
{
  static const char* value()
  {
    return DataType< ::Behaviors::ReserveBehavior >::value();
  }
  static const char* value(const ::Behaviors::ReserveBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Behaviors::ReserveBehaviorResponse> should match 
// service_traits::MD5Sum< ::Behaviors::ReserveBehavior > 
template<>
struct MD5Sum< ::Behaviors::ReserveBehaviorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Behaviors::ReserveBehavior >::value();
  }
  static const char* value(const ::Behaviors::ReserveBehaviorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Behaviors::ReserveBehaviorResponse> should match 
// service_traits::DataType< ::Behaviors::ReserveBehavior > 
template<>
struct DataType< ::Behaviors::ReserveBehaviorResponse>
{
  static const char* value()
  {
    return DataType< ::Behaviors::ReserveBehavior >::value();
  }
  static const char* value(const ::Behaviors::ReserveBehaviorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEHAVIORS_MESSAGE_RESERVEBEHAVIOR_H
