(cl:defpackage controllers-srv
  (:use )
  (:export
   "BASICARMPLAN"
   "<BASICARMPLAN-REQUEST>"
   "BASICARMPLAN-REQUEST"
   "<BASICARMPLAN-RESPONSE>"
   "BASICARMPLAN-RESPONSE"
   "ARMMOVE"
   "<ARMMOVE-REQUEST>"
   "ARMMOVE-REQUEST"
   "<ARMMOVE-RESPONSE>"
   "ARMMOVE-RESPONSE"
   "TESTSERVICE"
   "<TESTSERVICE-REQUEST>"
   "TESTSERVICE-REQUEST"
   "<TESTSERVICE-RESPONSE>"
   "TESTSERVICE-RESPONSE"
  ))

