(cl:defpackage controllers-srv
  (:use )
  (:export
   "ARMMOVE"
   "<ARMMOVE-REQUEST>"
   "ARMMOVE-REQUEST"
   "<ARMMOVE-RESPONSE>"
   "ARMMOVE-RESPONSE"
   "TESTSERVICE"
   "<TESTSERVICE-REQUEST>"
   "TESTSERVICE-REQUEST"
   "<TESTSERVICE-RESPONSE>"
   "TESTSERVICE-RESPONSE"
   "BASICARMMOVE"
   "<BASICARMMOVE-REQUEST>"
   "BASICARMMOVE-REQUEST"
   "<BASICARMMOVE-RESPONSE>"
   "BASICARMMOVE-RESPONSE"
  ))

