/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/vsunder/ButlerBot/catkin_ws/src/Intelligence/srv/RequestBehavior.srv
 *
 */


#ifndef INTELLIGENCE_MESSAGE_REQUESTBEHAVIOR_H
#define INTELLIGENCE_MESSAGE_REQUESTBEHAVIOR_H

#include <ros/service_traits.h>


#include <Intelligence/RequestBehaviorRequest.h>
#include <Intelligence/RequestBehaviorResponse.h>


namespace Intelligence
{

struct RequestBehavior
{

typedef RequestBehaviorRequest Request;
typedef RequestBehaviorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestBehavior
} // namespace Intelligence


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Intelligence::RequestBehavior > {
  static const char* value()
  {
    return "8c622a6f499ac0556a7e3ed8206e23ac";
  }

  static const char* value(const ::Intelligence::RequestBehavior&) { return value(); }
};

template<>
struct DataType< ::Intelligence::RequestBehavior > {
  static const char* value()
  {
    return "Intelligence/RequestBehavior";
  }

  static const char* value(const ::Intelligence::RequestBehavior&) { return value(); }
};


// service_traits::MD5Sum< ::Intelligence::RequestBehaviorRequest> should match 
// service_traits::MD5Sum< ::Intelligence::RequestBehavior > 
template<>
struct MD5Sum< ::Intelligence::RequestBehaviorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Intelligence::RequestBehavior >::value();
  }
  static const char* value(const ::Intelligence::RequestBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Intelligence::RequestBehaviorRequest> should match 
// service_traits::DataType< ::Intelligence::RequestBehavior > 
template<>
struct DataType< ::Intelligence::RequestBehaviorRequest>
{
  static const char* value()
  {
    return DataType< ::Intelligence::RequestBehavior >::value();
  }
  static const char* value(const ::Intelligence::RequestBehaviorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Intelligence::RequestBehaviorResponse> should match 
// service_traits::MD5Sum< ::Intelligence::RequestBehavior > 
template<>
struct MD5Sum< ::Intelligence::RequestBehaviorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Intelligence::RequestBehavior >::value();
  }
  static const char* value(const ::Intelligence::RequestBehaviorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Intelligence::RequestBehaviorResponse> should match 
// service_traits::DataType< ::Intelligence::RequestBehavior > 
template<>
struct DataType< ::Intelligence::RequestBehaviorResponse>
{
  static const char* value()
  {
    return DataType< ::Intelligence::RequestBehavior >::value();
  }
  static const char* value(const ::Intelligence::RequestBehaviorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTELLIGENCE_MESSAGE_REQUESTBEHAVIOR_H
