(cl:defpackage Intelligence-srv
  (:use )
  (:export
   "ENABLECOMS"
   "<ENABLECOMS-REQUEST>"
   "ENABLECOMS-REQUEST"
   "<ENABLECOMS-RESPONSE>"
   "ENABLECOMS-RESPONSE"
   "REQUESTBEHAVIOR"
   "<REQUESTBEHAVIOR-REQUEST>"
   "REQUESTBEHAVIOR-REQUEST"
   "<REQUESTBEHAVIOR-RESPONSE>"
   "REQUESTBEHAVIOR-RESPONSE"
   "STARTUP"
   "<STARTUP-REQUEST>"
   "STARTUP-REQUEST"
   "<STARTUP-RESPONSE>"
   "STARTUP-RESPONSE"
  ))

