/* Auto-generated by genmsg_cpp for file /home/pwei/Desktop/ButlerBot/rosbuild_ws/src/controllers/srv/arm_controller.srv */
#ifndef CONTROLLERS_SERVICE_ARM_CONTROLLER_H
#define CONTROLLERS_SERVICE_ARM_CONTROLLER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace controllers
{
template <class ContainerAllocator>
struct arm_controllerRequest_ {
  typedef arm_controllerRequest_<ContainerAllocator> Type;

  arm_controllerRequest_()
  : base(0)
  , shoulder(0)
  , shoulder1(0)
  , elbow(0)
  , elbow1(0)
  , wrist(0)
  , wrot(0)
  , grip(0)
  {
  }

  arm_controllerRequest_(const ContainerAllocator& _alloc)
  : base(0)
  , shoulder(0)
  , shoulder1(0)
  , elbow(0)
  , elbow1(0)
  , wrist(0)
  , wrot(0)
  , grip(0)
  {
  }

  typedef int16_t _base_type;
  int16_t base;

  typedef int16_t _shoulder_type;
  int16_t shoulder;

  typedef int16_t _shoulder1_type;
  int16_t shoulder1;

  typedef int16_t _elbow_type;
  int16_t elbow;

  typedef int16_t _elbow1_type;
  int16_t elbow1;

  typedef int16_t _wrist_type;
  int16_t wrist;

  typedef int16_t _wrot_type;
  int16_t wrot;

  typedef int16_t _grip_type;
  int16_t grip;


  typedef boost::shared_ptr< ::controllers::arm_controllerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controllers::arm_controllerRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct arm_controllerRequest
typedef  ::controllers::arm_controllerRequest_<std::allocator<void> > arm_controllerRequest;

typedef boost::shared_ptr< ::controllers::arm_controllerRequest> arm_controllerRequestPtr;
typedef boost::shared_ptr< ::controllers::arm_controllerRequest const> arm_controllerRequestConstPtr;



template <class ContainerAllocator>
struct arm_controllerResponse_ {
  typedef arm_controllerResponse_<ContainerAllocator> Type;

  arm_controllerResponse_()
  : success(false)
  {
  }

  arm_controllerResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::controllers::arm_controllerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controllers::arm_controllerResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct arm_controllerResponse
typedef  ::controllers::arm_controllerResponse_<std::allocator<void> > arm_controllerResponse;

typedef boost::shared_ptr< ::controllers::arm_controllerResponse> arm_controllerResponsePtr;
typedef boost::shared_ptr< ::controllers::arm_controllerResponse const> arm_controllerResponseConstPtr;


struct arm_controller
{

typedef arm_controllerRequest Request;
typedef arm_controllerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct arm_controller
} // namespace controllers

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controllers::arm_controllerRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controllers::arm_controllerRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controllers::arm_controllerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ac905efe303267c46f982709d9b792e6";
  }

  static const char* value(const  ::controllers::arm_controllerRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xac905efe303267c4ULL;
  static const uint64_t static_value2 = 0x6f982709d9b792e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::controllers::arm_controllerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/arm_controllerRequest";
  }

  static const char* value(const  ::controllers::arm_controllerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controllers::arm_controllerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 base\n\
int16 shoulder\n\
int16 shoulder1\n\
int16 elbow\n\
int16 elbow1\n\
int16 wrist\n\
int16 wrot\n\
int16 grip\n\
\n\
";
  }

  static const char* value(const  ::controllers::arm_controllerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::controllers::arm_controllerRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controllers::arm_controllerResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controllers::arm_controllerResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controllers::arm_controllerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::controllers::arm_controllerResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::controllers::arm_controllerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/arm_controllerResponse";
  }

  static const char* value(const  ::controllers::arm_controllerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controllers::arm_controllerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const  ::controllers::arm_controllerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::controllers::arm_controllerResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controllers::arm_controllerRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.base);
    stream.next(m.shoulder);
    stream.next(m.shoulder1);
    stream.next(m.elbow);
    stream.next(m.elbow1);
    stream.next(m.wrist);
    stream.next(m.wrot);
    stream.next(m.grip);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct arm_controllerRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controllers::arm_controllerResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct arm_controllerResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<controllers::arm_controller> {
  static const char* value() 
  {
    return "407a8b06ff8c582b34020cd9a18a6609";
  }

  static const char* value(const controllers::arm_controller&) { return value(); } 
};

template<>
struct DataType<controllers::arm_controller> {
  static const char* value() 
  {
    return "controllers/arm_controller";
  }

  static const char* value(const controllers::arm_controller&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<controllers::arm_controllerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "407a8b06ff8c582b34020cd9a18a6609";
  }

  static const char* value(const controllers::arm_controllerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<controllers::arm_controllerRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/arm_controller";
  }

  static const char* value(const controllers::arm_controllerRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<controllers::arm_controllerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "407a8b06ff8c582b34020cd9a18a6609";
  }

  static const char* value(const controllers::arm_controllerResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<controllers::arm_controllerResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/arm_controller";
  }

  static const char* value(const controllers::arm_controllerResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLERS_SERVICE_ARM_CONTROLLER_H

