/* Auto-generated by genmsg_cpp for file /home/peter/ButlerBot/rosbuild_ws/src/controllers/srv/armMove.srv */
#ifndef CONTROLLERS_SERVICE_ARMMOVE_H
#define CONTROLLERS_SERVICE_ARMMOVE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace controllers
{
template <class ContainerAllocator>
struct armMoveRequest_ {
  typedef armMoveRequest_<ContainerAllocator> Type;

  armMoveRequest_()
  : base()
  , shoulder()
  , elbow()
  , wrist()
  , wrot()
  , grip()
  {
  }

  armMoveRequest_(const ContainerAllocator& _alloc)
  : base(_alloc)
  , shoulder(_alloc)
  , elbow(_alloc)
  , wrist(_alloc)
  , wrot(_alloc)
  , grip(_alloc)
  {
  }

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _base_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  base;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _shoulder_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  shoulder;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _elbow_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  elbow;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _wrist_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  wrist;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _wrot_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  wrot;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _grip_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  grip;


  typedef boost::shared_ptr< ::controllers::armMoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controllers::armMoveRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct armMoveRequest
typedef  ::controllers::armMoveRequest_<std::allocator<void> > armMoveRequest;

typedef boost::shared_ptr< ::controllers::armMoveRequest> armMoveRequestPtr;
typedef boost::shared_ptr< ::controllers::armMoveRequest const> armMoveRequestConstPtr;



template <class ContainerAllocator>
struct armMoveResponse_ {
  typedef armMoveResponse_<ContainerAllocator> Type;

  armMoveResponse_()
  : success(false)
  {
  }

  armMoveResponse_(const ContainerAllocator& _alloc)
  : success(false)
  {
  }

  typedef uint8_t _success_type;
  uint8_t success;


  typedef boost::shared_ptr< ::controllers::armMoveResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controllers::armMoveResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct armMoveResponse
typedef  ::controllers::armMoveResponse_<std::allocator<void> > armMoveResponse;

typedef boost::shared_ptr< ::controllers::armMoveResponse> armMoveResponsePtr;
typedef boost::shared_ptr< ::controllers::armMoveResponse const> armMoveResponseConstPtr;


struct armMove
{

typedef armMoveRequest Request;
typedef armMoveResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct armMove
} // namespace controllers

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controllers::armMoveRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controllers::armMoveRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controllers::armMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5a7bbb0c83efa6b2a771da8ea8d8aa0c";
  }

  static const char* value(const  ::controllers::armMoveRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5a7bbb0c83efa6b2ULL;
  static const uint64_t static_value2 = 0xa771da8ea8d8aa0cULL;
};

template<class ContainerAllocator>
struct DataType< ::controllers::armMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/armMoveRequest";
  }

  static const char* value(const  ::controllers::armMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controllers::armMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32[] base\n\
float32[] shoulder\n\
float32[] elbow\n\
float32[] wrist\n\
float32[] wrot\n\
float32[] grip\n\
\n\
";
  }

  static const char* value(const  ::controllers::armMoveRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::controllers::armMoveResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::controllers::armMoveResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::controllers::armMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const  ::controllers::armMoveResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::controllers::armMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/armMoveResponse";
  }

  static const char* value(const  ::controllers::armMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::controllers::armMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool success\n\
\n\
\n\
";
  }

  static const char* value(const  ::controllers::armMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::controllers::armMoveResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controllers::armMoveRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.base);
    stream.next(m.shoulder);
    stream.next(m.elbow);
    stream.next(m.wrist);
    stream.next(m.wrot);
    stream.next(m.grip);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct armMoveRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::controllers::armMoveResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.success);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct armMoveResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<controllers::armMove> {
  static const char* value() 
  {
    return "12ec2c38c4b52f54cb430d38cc34d7d4";
  }

  static const char* value(const controllers::armMove&) { return value(); } 
};

template<>
struct DataType<controllers::armMove> {
  static const char* value() 
  {
    return "controllers/armMove";
  }

  static const char* value(const controllers::armMove&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<controllers::armMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "12ec2c38c4b52f54cb430d38cc34d7d4";
  }

  static const char* value(const controllers::armMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<controllers::armMoveRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/armMove";
  }

  static const char* value(const controllers::armMoveRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<controllers::armMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "12ec2c38c4b52f54cb430d38cc34d7d4";
  }

  static const char* value(const controllers::armMoveResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<controllers::armMoveResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "controllers/armMove";
  }

  static const char* value(const controllers::armMoveResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // CONTROLLERS_SERVICE_ARMMOVE_H

